# This is a basic workflow to help you get started with Actions

name: releases

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "origin" branch
  push:
    branches: origin


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: semver
        id: semver # required to use the output in other steps
        uses: grumpy-programmer/conventional-commits-semver-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: push
        if: ${{ steps.semver.outputs.released == 'true' }}
        run: |
         echo  Release Generated
